"""Canonical national-team flag assets for the Streamlit application."""

from urllib.parse import quote, unquote


NO_IMAGE_URL = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg"
WIKIMEDIA_FILE_BASE_URL = "https://commons.wikimedia.org/wiki/Special:FilePath/"

TEAM_FLAG_FILES: dict[str, str] = {
    'Afghanistan': 'File:Flag_of_the_Taliban.svg',
    'Albania': 'File:Flag_of_Albania.svg',
    'Algeria': 'File:Flag_of_Algeria.svg',
    'Samoa': 'File:Flag_of_Samoa.svg',
    'Andorra': 'File:Flag_of_Andorra.svg',
    'Angola': 'File:Flag_of_Angola.svg',
    'Anguilla': 'File:Flag_of_Anguilla.svg',
    'Antigua and Barbuda': 'File:Flag_of_Antigua_and_Barbuda.svg',
    'Argentina': 'File:Flag_of_Argentina.svg',
    'Armenia': 'File:Flag_of_Armenia.svg',
    'Aruba': 'File:Flag_of_Aruba.svg',
    'Australia': 'File:Flag_of_Australia.svg',
    'Austria': 'File:Flag_of_Austria.svg',
    'Azerbaijan': 'File:Flag_of_Azerbaijan.svg',
    'Bahamas': 'File:Flag_of_Bahamas.svg',
    'Bahrain': 'File:Flag_of_Bahrain.svg',
    'Bangladesh': 'File:Flag_of_Bangladesh.svg',
    'Barbados': 'File:Flag_of_Barbados.svg',
    'Basque Country': 'File:Flag_of_the_Basque_Country.svg',
    'Belarus': 'File:Flag_of_Belarus.svg',
    'Belgium': 'File:Flag_of_Belgium.svg',
    'Belize': 'File:Flag_of_Belize.svg',
    'Benin': 'File:Flag_of_Benin.svg',
    'Bermuda': 'File:Flag_of_Bermuda.svg',
    'Bhutan': 'File:Flag_of_Bhutan.svg',
    'Bolivia': 'File:Flag_of_Bolivia.svg',
    'Bonaire': 'File:Flag_of_Bonaire.svg',
    'Bosnia and Herzegovina': 'File:Flag_of_Bosnia_and_Herzegovina.svg',
    'Botswana': 'File:Flag_of_Botswana.svg',
    'Brazil': 'File:Flag_of_Brazil.svg',
    'British Virgin Islands': 'File:Flag_of_the_British_Virgin_Islands.svg',
    'Brunei': 'File:Flag_of_Brunei.svg',
    'Bulgaria': 'File:Flag_of_Bulgaria.svg',
    'Burkina Faso': 'File:Flag_of_Burkina_Faso.svg',
    'Burundi': 'File:Flag_of_Burundi.svg',
    'Cambodia': 'File:Flag_of_Cambodia.svg',
    'Cameroon': 'File:Flag_of_Cameroon.svg',
    'Canada': 'File:Flag_of_Canada.svg',
    'Cape Verde Islands': 'File:Flag_of_Cape_Verde.svg',
    'Cayman Islands': 'File:Flag_of_the_Cayman_Islands.svg',
    'Central African Republic': 'File:Flag_of_the_Central_African_Republic.svg',
    'Chad': 'File:Flag_of_Chad.svg',
    'Chile': 'File:Flag_of_Chile.svg',
    'China PR': 'File:Flag_of_the_People%27s_Republic_of_China.svg',
    'Chinese Taipei': 'File:Flag_of_the_Republic_of_China.svg',
    'Colombia': 'File:Flag_of_Colombia.svg',
    'Comoros': 'File:Flag_of_Comoros.svg',
    'Congo': 'File:Flag_of_the_Republic_of_the_Congo.svg',
    'Congo DR': 'File:Flag_of_the_Democratic_Republic_of_the_Congo.svg',
    'Cook Islands': 'File:Flag_of_the_Cook_Islands.svg',
    'Costa Rica': 'File:Flag_of_Costa_Rica.svg',
    'Croatia': 'File:Flag_of_Croatia.svg',
    'Cuba': 'File:Flag_of_Cuba.svg',
    'Curacao': 'File:Flag_of_Cura%C3%A7ao.svg',
    'Cyprus': 'File:Flag_of_Cyprus.svg',
    'Czech Republic': 'File:Flag_of_the_Czech_Republic.svg',
    'Denmark': 'File:Flag_of_Denmark.svg',
    'Djibouti': 'File:Flag_of_Djibouti.svg',
    'Dominica': 'File:Flag_of_Dominica.svg',
    'Dominican Republic': 'File:Flag_of_the_Dominican_Republic.svg',
    'Ecuador': 'File:Flag_of_Ecuador.svg',
    'Egypt': 'File:Flag_of_Egypt.svg',
    'El Salvador': 'File:Flag_of_El_Salvador.svg',
    'England': 'File:Flag_of_England.svg',
    'Equatorial Guinea': 'File:Flag_of_Equatorial_Guinea.svg',
    'Eritrea': 'File:Flag_of_Eritrea.svg',
    'Estonia': 'File:Flag_of_Estonia.svg',
    'Ethiopia': 'File:Flag_of_Ethiopia.svg',
    'Faroe Islands': 'File:Flag_of_the_Faroe_Islands.svg',
    'Fiji': 'File:Flag_of_Fiji.svg',
    'Finland': 'File:Flag_of_Finland.svg',
    'France': 'File:Flag_of_France.svg',
    'French Guiana': 'File:Flag_of_French_Guiana.svg',
    'Gabon': 'File:Flag_of_Gabon.svg',
    'Gambia': 'File:Flag_of_The_Gambia.svg',
    'Georgia': 'File:Flag_of_Georgia.svg',
    'Germany': 'File:Flag_of_Germany.svg',
    'Ghana': 'File:Flag_of_Ghana.svg',
    'Gibraltar': 'File:Flag_of_Gibraltar.svg',
    'Greece': 'File:Flag_of_Greece.svg',
    'Grenada': 'File:Flag_of_Grenada.svg',
    'Guadeloupe': 'File:Unofficial_flag_of_Guadeloupe_%28local%29.svg',
    'Guam': 'File:Flag_of_Guam.svg',
    'Guatemala': 'File:Flag_of_Guatemala.svg',
    'Guinea': 'File:Flag_of_Guinea.svg',
    'Guinea-Bissau': 'File:Flag_of_Guinea-Bissau.svg',
    'Guyana': 'File:Flag_of_Guyana.svg',
    'Haiti': 'File:Flag_of_Haiti.svg',
    'Honduras': 'File:Flag_of_Honduras_%282022-%29.svg',
    'Hong Kong': 'File:Flag_of_Hong_Kong.svg',
    'Hungary': 'File:Flag_of_Hungary.svg',
    'Iceland': 'File:Flag_of_Iceland.svg',
    'India': 'File:Flag_of_India.svg',
    'Indonesia': 'File:Flag_of_Indonesia.svg',
    'Iran': 'File:Flag_of_Iran.svg',
    'Iraq': 'File:Flag_of_Iraq.svg',
    'Israel': 'File:Flag_of_Israel.svg',
    'Italy': 'File:Flag_of_Italy.svg',
    'Ivory Coast': 'File:Flag_of_Côte_d%27Ivoire.svg',
    'Jamaica': 'File:Flag_of_Jamaica.svg',
    'Japan': 'File:Flag_of_Japan.svg',
    'Jordan': 'File:Flag_of_Jordan.svg',
    'Kazakhstan': 'File:Flag_of_Kazakhstan.svg',
    'Kenya': 'File:Flag_of_Kenya.svg',
    'Kosovo': 'File:Flag_of_Kosovo.svg',
    'Kuwait': 'File:Flag_of_Kuwait.svg',
    'Kyrgyzstan': 'File:Flag_of_Kyrgyzstan.svg',
    'Laos': 'File:Flag_of_Laos.svg',
    'Latvia': 'File:Flag_of_Latvia.svg',
    'Lebanon': 'File:Flag_of_Lebanon.svg',
    'Lesotho': 'File:Flag_of_Lesotho.svg',
    'Liberia': 'File:Flag_of_Liberia.svg',
    'Libya': 'File:Flag_of_Libya.svg',
    'Liechtenstein': 'File:Flag_of_Liechtenstein.svg',
    'Lithuania': 'File:Flag_of_Lithuania.svg',
    'Luxembourg': 'File:Flag_of_Luxembourg.svg',
    'Macau': 'File:Flag_of_Macau.svg',
    'Madagascar': 'File:Flag_of_Madagascar.svg',
    'Malawi': 'File:Flag_of_Malawi.svg',
    'Malaysia': 'File:Flag_of_Malaysia.svg',
    'Maldives': 'File:Flag_of_Maldives.svg',
    'Mali': 'File:Flag_of_Mali.svg',
    'Malta': 'File:Flag_of_Malta.svg',
    'Martinique': 'File:Flag_of_the_Territorial_Collectivity_of_Martinique.svg',
    'Mauritania': 'File:Flag_of_Mauritania.svg',
    'Mauritius': 'File:Flag_of_Mauritius.svg',
    'Mexico': 'File:Flag_of_Mexico.svg',
    'Moldova': 'File:Flag_of_Moldova.svg',
    'Mongolia': 'File:Flag_of_Mongolia.svg',
    'Montenegro': 'File:Flag_of_Montenegro.svg',
    'Montserrat': 'File:Flag_of_Montserrat.svg',
    'Morocco': 'File:Flag_of_Morocco.svg',
    'Mozambique': 'File:Flag_of_Mozambique.svg',
    'Myanmar': 'File:Flag_of_Myanmar.svg',
    'Namibia': 'File:Flag_of_Namibia.svg',
    'Nepal': 'File:Flag_of_Nepal.svg',
    'Netherlands': 'File:Flag_of_the_Netherlands.svg',
    'New Caledonia': 'File:Flag_of_FLNKS.svg',
    'New Zealand': 'File:Flag_of_New_Zealand.svg',
    'Nicaragua': 'File:Flag_of_Nicaragua.svg',
    'Niger': 'File:Flag_of_Niger.svg',
    'Nigeria': 'File:Flag_of_Nigeria.svg',
    'North Korea': 'File:Flag_of_North_Korea.svg',
    'North Macedonia': 'File:Flag_of_North_Macedonia.svg',
    'Northern Ireland': 'File:Saint_Patrick%27s_Saltire.svg',
    'Northern Mariana Islands': 'File:Flag_of_the_Northern_Mariana_Islands.svg',
    'Norway': 'File:Flag_of_Norway.svg',
    'Oman': 'File:Flag_of_Oman.svg',
    'Pakistan': 'File:Flag_of_Pakistan.svg',
    'Palestine': 'File:Flag_of_Palestine.svg',
    'Panama': 'File:Flag_of_Panama.svg',
    'Papua New Guinea': 'File:Flag_of_Papua_New_Guinea.svg',
    'Paraguay': 'File:Flag_of_Paraguay.svg',
    'Peru': 'File:Flag_of_Peru.svg',
    'Philippines': 'File:Flag_of_the_Philippines.svg',
    'Poland': 'File:Flag_of_Poland.svg',
    'Portugal': 'File:Flag_of_Portugal.svg',
    'Puerto Rico': 'File:Flag_of_Puerto_Rico.svg',
    'Qatar': 'File:Flag_of_Qatar.svg',
    'Rep of Ireland': 'File:Flag_of_Ireland.svg',
    'Romania': 'File:Flag_of_Romania.svg',
    'Russia': 'File:Flag_of_Russia.svg',
    'Rwanda': 'File:Flag_of_Rwanda.svg',
    'San Marino': 'File:Flag_of_San_Marino.svg',
    'Sao Tome and Principe': 'File:Flag_of_Sao_Tome_and_Principe.svg',
    'Saudi Arabia': 'File:Flag_of_Saudi_Arabia.svg',
    'Scotland': 'File:Flag_of_Scotland.svg',
    'Senegal': 'File:Flag_of_Senegal.svg',
    'Serbia': 'File:Flag_of_Serbia.svg',
    'Seychelles': 'File:Flag_of_Seychelles.svg',
    'Sierra Leone': 'File:Flag_of_Sierra_Leone.svg',
    'Singapore': 'File:Flag_of_Singapore.svg',
    'Sint Maarten': 'File:Flag_of_Sint_Maarten.svg',
    'Slovakia': 'File:Flag_of_Slovakia.svg',
    'Slovenia': 'File:Flag_of_Slovenia.svg',
    'Solomon Islands': 'File:Flag_of_Solomon_Islands.svg',
    'Somalia': 'File:Flag_of_Somalia.svg',
    'South Africa': 'File:Flag_of_South_Africa.svg',
    'South Korea': 'File:Flag_of_South_Korea.svg',
    'South Sudan': 'File:Flag_of_South_Sudan.svg',
    'Spain': 'File:Flag_of_Spain.svg',
    'Sri Lanka': 'File:Flag_of_Sri_Lanka.svg',
    'St. Kitts and Nevis': 'File:Flag_of_Saint_Kitts_and_Nevis.svg',
    'St. Lucia': 'File:Flag_of_Saint_Lucia.svg',
    'St. Martin': 'File:Local_flag_of_the_Collectivity_of_Saint_Martin.svg',
    'St. Vincent and the Grenadines': 'File:Flag_of_Saint_Vincent_and_the_Grenadines.svg',
    'Sudan': 'File:Flag_of_Sudan.svg',
    'Suriname': 'File:Flag_of_Suriname.svg',
    'Swaziland': 'File:Flag_of_Eswatini.svg',
    'Sweden': 'File:Flag_of_Sweden.svg',
    'Switzerland': 'File:Flag_of_Switzerland.svg',
    'Syria': 'File:Flag_of_Syria.svg',
    'Tahiti': 'File:Flag_of_Tahiti.svg',
    'Tajikistan': 'File:Flag_of_Tajikistan.svg',
    'Tanzania': 'File:Flag_of_Tanzania.svg',
    'Thailand': 'File:Flag_of_Thailand.svg',
    'Timor-Leste': 'File:Flag_of_East_Timor.svg',
    'Togo': 'File:Flag_of_Togo.svg',
    'Tonga': 'File:Flag_of_Tonga.svg',
    'Trinidad and Tobago': 'File:Flag_of_Trinidad_and_Tobago.svg',
    'Tunisia': 'File:Flag_of_Tunisia.svg',
    'Turkey': 'File:Flag_of_Turkey.svg',
    'Turkmenistan': 'File:Flag_of_Turkmenistan.svg',
    'Turks and Caicos Islands': 'File:Flag_of_the_Turks_and_Caicos_Islands.svg',
    'Tuvalu': 'File:Flag_of_Tuvalu.svg',
    'Uganda': 'File:Flag_of_Uganda.svg',
    'Ukraine': 'File:Flag_of_Ukraine.svg',
    'United Arab Emirates': 'File:Flag_of_the_United_Arab_Emirates.svg',
    'Uruguay': 'File:Flag_of_Uruguay.svg',
    'US Virgin Islands': 'File:Flag_of_the_United_States_Virgin_Islands.svg',
    'USA': 'File:Flag_of_the_United_States.svg',
    'Uzbekistan': 'File:Flag_of_Uzbekistan.svg',
    'Vanuatu': 'File:Flag_of_Vanuatu.svg',
    'Venezuela': 'File:Flag_of_Venezuela.svg',
    'Vietnam': 'File:Flag_of_Vietnam.svg',
    'Wales': 'File:Flag_of_Wales.svg',
    'Yemen': 'File:Flag_of_Yemen.svg',
    'Zambia': 'File:Flag_of_Zambia.svg',
    'Zanzibar': 'File:Flag_of_Zanzibar.svg',
    'Zimbabwe': 'File:Flag_of_Zimbabwe.svg',
}


def wikimedia_file_url(file_name: str | None) -> str:
    if not file_name:
        return NO_IMAGE_URL
    return WIKIMEDIA_FILE_BASE_URL + quote(unquote(file_name), safe=":/.")


def flag_url_for_team(team: str) -> str:
    return wikimedia_file_url(TEAM_FLAG_FILES.get(team))
